# Jekyllサイトの基本設定

# サイト情報
title: Ryota Kataoka’s Research
author: Ryota Kataoka
email: r.kataoka@g.matsuyama-u.ac.jp
description: >- # descriptionは複数行にわたって記述できます
  Jekyllを使用した実験結果の報告ページです。
  このテンプレートは、研究成果をウェブ上で共有するために作成されました。
url: "https://cutter0715.github.io" # あなたのサイトのURL
baseurl: "" # リポジトリ名が `username.github.io` でない場合は、ここにリポジトリ名を入力 (例: /my-project)

# Markdownプロセッサの設定
markdown: kramdown

# テーマ (今回はカスタムCSSを使用するため指定なし)
# theme: minima

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-seo-tag
