project:
  type: website

website:
  title: "Experiment of target adjustment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plan.qmd
        text: 実験計画
      - href: pilot.qmd
        text: パイロットテスト
      - href: results.qmd
        text: 本実験
