---
title: "目標の期中調整 実験"
author: "片岡　亮太"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
editor: visual
date: now
date-format: YYYY/MM/DD, HH:mm
toc: true
toc-depth: 5
toc-location: left
toc-title: Contents
number-sections: true
number-depth: 5
code-fold: true
link-citations: true
---

## 実験計画の概要

### 前回の実験結果

-   仮説1：期待効果で予想されたマイナスの効果は有意な結果ではなかった。
-   仮説2：実施効果で予想されたプラスの効果ではなくマイナスの効果が一部出た。

### 前回の問題点

共通の原因 - 固定報酬に対して変動分が小さいので業績を高めるインセンティブが小さかった。 - 全員に一定の目標値を設定していたため，目標の難易度が被験者間で異なる（同じ目標でも被験者の能力によって簡単すぎる人と目標が難しすぎる人がいた）。 仮説1の結果が出なかった原因 -期中調整の告知の内容が抽象的だったため，参加者は期中調整が行われることを十分に信じておらず努力を控えなかった。 仮説2の結果が出なかった（一部逆の結果になった）原因 -期中調整の実施によって実際に目標が下がったことで気が緩まり，本来実施効果で予想していたプラスの効果ではなく，マイナスの効果が生じる可能性がある。

### 改善点

-   仮説の精緻化 -告知効果は管理不能要因の有無で変化する。
-   前回の実験では，業績と公正の間に正の相関が見られた。先行研究で扱われている公正も仮説に入れる。
-   参加者ごとの個別目標を設定
-   実験開始前に練習パートを実施し，各参加者の能力を計測。
-   この練習パートに基づいて，参加者個別の目標値を設定する（このことは参加者には伝えない）。
-   練習パートの正解数に連動報酬を与える。
-   報酬設計の改善
-   実験参加者への変動報酬部分で大きく報酬を与える。
-   
-   報酬の上限は前回同様に設定しない。これは，前半期間に上限近くの業績を達成してしまうと後半に努力を控える可能性はあるため。また，目標値以外に参照点を与えると実験が複雑になるため。 -厳しい期間の得点は大きく下がるように調整する。
-   期中調整の情報の伝え方を改善する。調整する確率（50％）を具体的に参加者に伝える。

### 早川先生（20250611）

-   平常ラウンドと厳しいラウンドが参加者にわかりにくいのではないか。
-   期中調整の文言が曖昧ではないか。50％という確率の数字を入れるか，具体的な調整の程度を入れるか -「適切な難易度まで下方調整する」入れる
-   平常ラウンドと厳しいラウンドが問題の比率1：3と3：1ではあまり難易度の差が生まれないのではないか。 -パイロットテストで確認する。
-   1ラウンド2分（前後半1分）は短くないか。1分で環境を判断できるか。 -前後半2分合計4分間に戻す。
-   デコーディングタスク1ケタは短すぎないか。一定の桁数があって初めて認知的負荷がかかるのではないか。元論文やタスクに関する論文を確認した方が良い。 -Choi et al. (2018) を確認して，3桁で行う。ただし，Choi et al. (2018) は数字3桁→アルファベット1文字のデコーディングタスクを行っている 。これでは，難易度の変更がしにくい。
-   練習ラウンドの業績で報酬を与える，告知あり-実施なし条件は研究倫理に触れないか
-   仮説3a→告知ありとなしで公正の認識は変わるか。
-   目標難易度が適切なのか（練習ラウンドの業績の100％）はパイロットテストで確認した方が良い。 -パイロットテストで確認する。

佐久間先生（20250612） -練習ラウンドと本番ラウンドで報酬契約の形態を変えることに問題があるのではないか。練習ラウンドと本番ラウンドで努力の仕方が変わる可能性。 -練習ラウンドのスコアを目標値に使うことを参加者に示さないことの倫理的問題がありそう。 -タスクの難易度ではなく，最初に設定する目標の難易度を変化させてはどうか。そちらのほうが実験の設定を単純にできるし，受注量などの設定では現実にもありえそう。目標の難易度を変えれば，1人1人の目標難易度が適切かどうかの問題をある程度クリアできそう。ただし，環境変化という現在の設定が変わってしまうこととどのくらい期中調整するのかという問題が難しくなる。

## 仮説

### 目標の期中調整の期待と実施の効果

会計学や心理学の多くの研究は，困難だが達成可能な目標が業績に正の効果をもたらすことを示唆している(Locke and Latham 1990, Locke and Latham 2002, Bonner and Sprinkle, 2002, Hirst and Lowy 1990）。目標は，注意を相関する活動に向けさせ，より大きな努力と持続的な努力を誘発し，タスクに相関する知識の使用につながる（Locke and Latham 1990, Locke and Latham 2002）。 しかし，目標を期首に設定した後に，予測できなかった管理不能要因（経済的要因，競合の行動など）が発生することがあり，目標の難易度が達成不可能な水準まで上がる可能性がある（Gibbs et al. 2004）。このとき，標達成と報酬を結びつけているならば，従業員の努力を減退させる可能性がある。したがって，事後的に管理不能要因を考慮し，事前の目標難易度を回復する調整を行うことで，目標の難易度を改善することができる（Hoppe and Moers 2011; Murphy and Oyer 2003）。これを目標の期中調整(intra-year target adjustments)という(Arnold and Artz 2015)。 期中調整が従業員の努力に対して与える効果は，正と負の予測の両方が存在する。正の効果の予測は，前述したとおり，経済状況の変化に応じて年度内に目標が調整されれば，財務的なインセンティブが再調整されることになるということである(Milgrom and Roberts 1992）。事後的に管理不能要因を考慮し，事前の目標難易度まで回復する調整を行うことで，インセンティブ契約を改善することができる（Hoppe and Moers 2011, Murphy and Oyer 2003）。 一方，負の効果の予測は，従業員が期待する期中調整の可能性が高まると，期首に設定された目標へのコミットメントが弱くなるということである()。目標の期中調整は，経済学的に事後的な再交渉を意味する(Milgrom and Roberts 1992)。 また，実証研究の結果も分かれている。事後的な目標の調整は手続き的公正を高めることを通じて従業員の努力を高めることが示している(Kelly et al. 2015)。一方，企業レベルのアーカイバル研究では，期中に予算目標を調整する度合いが，企業業績と負の相関があることがわかっている (Arnold and Artz 2015)。 これらの対立的な理論的予測は期中調整の効果をひとまとめとして扱っている。また，これまでの実証研究では実際に期中に目標を調整する前と後に分けて業績を測定していない。このことにより，目標の期中調整が業績に与える効果を十分に理解できていないという問題がある。 そこで本研究では，目標の期中調整が個人の努力に対して与える影響を目標の調整前の期待による効果と実際に調整した後の実施による効果の2つに分けて考える。 まず，目標の調整前の期待による効果について考える。通常は，期中調整の期待をもつ従業員は，期中調整の期待もたない従業員と比較して負の効果をもつと考えられる。従業員が期待する目標の期中調整の可能性が高まると，期首に設定された目標へのコミットメントが弱くなる。目標の期中調整の前に従業員が目標の期中調整について何らかの情報を持っている場合，期中に目標が下方に調整されるだろうという期待が生じる。したがって，期首から目標が実際に調整されるまでの時点の間，従業員が知覚する目標の難易度は低下する（仮説1a）。管理不能要因が発生せず期首の目標の難易度が最適な場合は，従業員の認識する目標の難易度が低下する。この場合，目標の難易度は容易な水準に下がってしまう。その結果，従業員は努力を引き下げる。したがって，目標の期中調整の事前の期待は，管理不能要因が発生する場合は努力を引き上げ，管理不能要因が発生しない場合は期間の前半の努力を引き下げると予測できる。一方，管理不能要因が発生し期首の目標の難易度が高すぎる場合は，従業員が認識する目標の難易度が低下することにより目標の難易度は達成可能な範囲で困難な最適な水準である。その結果，従業員は努力を引き上げる。したがって，管理不能要因が発生する場合は，目標の期中調整の事前の期待は，期間前半の努力を引き上げると予測できる（仮説1b）。

-   仮説1a： 管理不能要因のない期間に，目標の期中調整の期待がある場合，期待がない場合と比較して，期間の前半の業績は低い。
-   仮説1b： 管理不能要因のある期間に，目標の期中調整の期待がある場合，期待がない場合と比較して，期間の前半の業績は高い。

次に，実際に目標が調整された後の場合の効果を考える。管理不能要因の発生によって，目標の難易度が高すぎて達成不可能であるとき，従業員の努力水準は低くなる。そこから目標が最適な目標水準に実際に調整されると，従業員が認識する目標の難易度は最適な水準に回復し，従業員の努力を引き上げる。したがって，管理不能要因が発生する場合の目標の期中調整の実施は，後半の努力を引き上げると予測できる（仮説2）。

-   仮説2： 管理不能要因のある期間に目標の期中調整を実施する場合，実施しない場合と比較して，期間の後半の業績が高い。

### 目標の期中調整と公正の関係

評価手続きと関連する結果の公平さ(fairness)に対する従業員の認識は，業績評価と報酬制度に対する従業員の反応に影響する重要な要素である(Latham et al. 2005)。組織的公正(organization justice)は，分配的公正(distributive justice)と手続き的公正（procedural justice）および相互作用的公正(interactional justice)の認識から構成される（(Leventhal 1980, Beugré and Baron 2001, Greenberg 1986）。手続き的公正は，業績が評価され，報酬が与えられるプロセスの公正の認識に関係し，分配的公正は，貢献した仕事（努力，品質など）に対する評価や受け取った報酬などの結果の公正の認識に関係する（Colquitt et al. 2006）。相互作用的公正(interactional justice)は，上司と部下の間の相互関係に関係する(Beugré and Baron 2001)。 期中調整に関する先行研究の1つであるKelly et al. (2015)は，その中でも手続き的公正の認識に焦点を当てている。業績結果に影響を与えうる管理不能要因がある場合に，業績評価と報酬に用いられるプロセスに関係するからである。また，先行研究は，従業員の手続き的公正の認知が，分配的公正の認知ではなく，雇用主の全体的な公正に対する従業員の認識を決定し，それが雇用主に対する従業員の態度や行動に影響を与えることを示している（Beugré and Baron 2001）。Kelly et al. (2015)は，目標の事後的な調整が手続き的公正を高め，結果として業績を高めることを実証した。本研究も期中調整と手続き的公正の関係に焦点を当てる。 社会的交換理論によれば，従業員と雇用主の関係は，各当事者が他者からの公正な利益と引き換えに満たす義務によって特徴付けられる（Blau 1964）。目標達成に対してボーナスが与えられる報酬制度では，雇用主は従業員の目標達成に報酬を支払う義務を負い，従業員は目標達成のために合理的な努力をする義務を負っている。しかし，業績に悪影響を及ぼす管理不能要因があると，事前に設定された目標の達成とそれに伴う報酬を受け取る可能性はかなり低くなる（Gibbs et al. 2008）。 したがって，期中調整は手続き的公正の知覚に正の効果をもたらすと予想される。期中調整は管理不能要因の影響を除去するために使用され，期中調整を行うことで期中調整を行わない場合に比べて目標達成率が高くなると仮定すれば，従業員は評価プロセスの公正性についてより好ましい認識を持つ可能性が高い。従業員は期中調整を経験する前に，期中調整の期待によって，将来，管理不能要因が起こったときに，その調整の有益な効果を予測し，手続き的公正の認識を形成することができる。さらに，これらの手続き的公正の認識は，従業員が実際に管理不能要因と期中調整の実施を経験したときに，さらに影響を受ける可能性が高い。したがって，仮説3aと3bは，従業員が期中調整を経験する前に手続き的公正の認識が形成されるという期待によるものと，さらに期中調整の実施によるもので形成される。一方，期中調整の期待と実施の不一致は，多期間において手続き的公正の認識に負の効果をもたらすと予想される。手続き的公正では，報酬分配に関連する手続きの一貫性が重視される(Beugré and Baron 2001)。期中調整の期待がある状態で期中調整の実施が行われないのは報酬分配に関連する手続きの一貫性を欠いている。したがって，手続き的公正の認識を低くすると予想される（仮説3b）。 また，公正は業績に影響を与えると考えられる。先行研究は，業績評価プロセスがより公正である（すなわち手続き的公正が高い）と認識する従業員は，自分の評価に満足し，自分の業績を向上させようとするモチベーションが高く，組織に留まる意思が強いことを示している（Libby 2001, Dailey and Kirk 1992, Taylor et al. 1995)。したがって，期中調整の効果は，手続き的公正の認識によって媒介して業績を高めると予想される。 管理不能要因がある期間だけでなく，管理不能要因がない期間にも期中調整が影響すると予想する理論的根拠は公正ヒューリスティック理論から導かれる。公正ヒューリスティック理論によると，人々は，プロセスの公平さに対する最初の評価を，プロセスを担当する組織の手続き的公正を総合的に評価するためのヒューリスティックとして使用し，それが組織に対する彼らの態度や行動を決定する(Beugré and Baron 2001, Lind et al. 1993) という。さらに，人と組織の相互作用の初期に得られるプロセス情報は，その後の情報よりも組織の全体的な公正の評価に影響を与える（Van den Bos et al. 1997, Lind and Tyler 1988, 228）。もし人々が，雇用主との相互作用の初期に形成された事後的な目標調整に関連する手続き的公正の認識を，より一般的に雇用主に帰属させるとすれば，この効果は管理不能要因がない期間にも存在する可能性がある。したがって仮説4は管理不能要因の有無に関連していない。

-   仮説3a： 目標の期中調整の期待があり，管理不能要因がある期間に目標の期中調整を実施する場合，目標の期中調整の期待がなく管理不能要因がある期間に目標の期中調整を実施する場合と比較して手続き的公正の認識が高い。
-   仮説3b： 目標の期中調整の期待がなく，管理不能要因がある期間に目標の期中調整を実施する場合，目標の期中調整の期待がなく管理不能要因がある期間に目標の期中調整を実施しない場合と比較して手続き的公正の認識が高い。
-   仮説3c： 目標の期中調整の期待があり，管理不能要因がある期間に目標の期中調整を実施しない場合，目標の期中調整の期待がなく管理不能要因がある期間に目標の期中調整を実施しない場合と比較して手続き的公正の認識が低い。
-   仮説4： 目標の期中調整の期待と実施の組み合わせは，従業員の手続き的公正性の認識を媒介して，全期間の業績を高める。

  \### 条件別の難易度の予想

###条件別の業績の予想

  ###条件別の予測 平常ラウンド 期中調整 業績 手続き的 公正 全体の 業績 告知 実施 前半 後半\
あり あり／なし 低 ？ 高 中 なし あり／なし 高 ？ 低 高

厳しいラウンド 期中調整 業績 手続き的 公正 全体の 業績 告知 実施 前半 後半\
あり あり 高 高 中 中 なし 高 低 低 低 なし あり 低 高 高 高 なし 低 低 中 中

## リサーチ・デザイン

### 実験の概要

本研究は，オンライン実験によって仮説を検証する。なお，実験はPythonをベースとした実験用フレームワークであるoTree (Chen et al. 2016)を使用する。実験は，期中調整の告知（あり／なし）と期中調整の実施（あり／なし）の2×2参加者間要因で構成される。実験参加者はそれぞれの条件に無作為に割り当てられる。目標の期中調整の「告知あり」の条件は，参加者に「あなたは50％の確率で目標を下方調整される可能性がある」と説明される。目標の期中調整の「実施あり」の条件は，厳しい環境のラウンドの前半と後半の中間に目標が下方調整される。

### 実験参加者

1条件50人×4条件で，合計200人の実験参加者を集める。実験の参加者の募集および報酬の支払いは，研究用のクラウドソーシングプラットフォームであるProlificを使用する。実験の使用言語が英語であるため，対象者は米国および英国居住者に限定する。 実験のタスクと手順 実験で行うタスクは，リアル-エフォート-タスクの一種であるデコーディング-タスク(Chow 1983)である。デコーディング-タスクとは，数字とアルファベットの組み合わせ表に基づいて，数字をアルファベットに変換するタスクである。参加者は，数字とアルファベットの対応表を用いて，数字をアルファベットに変換する。不正解の場合は次の問題に進み，スコアにはカウントされない。また，画面にはそのラウンドの現時点の正解数と残り時間が表示される。 デコーディング-タスクによって参加者のパフォーマンスを測定する理由は，先行研究で行われているため比較が容易であるからであるからである。また，参加者の努力に敏感で，容易に学習でき，参加者が自分の能力を正確に測定することができる。 デコーディング-タスクの種類は，数字のケタが3ケタの問題と6ケタの問題があり，後者の方が解答により多くの時間を必要とする。参加者に対してこのラウンドが平常ラウンドであるか厳しいラウンドであるかはタスク中の画面に明示されない。平常ラウンドが3ケタ、厳しいラウンドが6ケタである。したがって，平常ラウンドと比較して厳しいラウンドは，目標を達成するのが難しくなることで，管理不能要因のある環境を再現している。したがって管理不能要因がある厳しいラウンドでは目標の期中調整が必要であるが，管理不能要因がない平常ラウンドでは必要ない。

【実験画面のイメージ】

【実験手順】 1. 参加者が実験への参加を承諾する。 2. 実験のタスクについて説明する。 3. 報酬条件について説明する。 4. 「告知あり」条件の群に対して，期中調整について説明をする。 5. 理解度確認テストを実施する。 6. 練習パート（2分×3回）を実施する。 7. 本番パートを実施する（①〜⑥の繰り返し4回）。 ① 目標を設定する。 ② ラウンド前半のタスクを行う（2分） ③ 目標の難易度に関する質問を行う。 ④ 期中調整する群に期中調整を行う。 ⑤ 目標の難易度に関する質問を行う。 ⑥ ラウンド後半のタスクを行う（2分）。 8. 参加者の背景と公正性に関する事後質問を行う。 9. 練習パートと本番パートの業績に基づいて報酬額を確定させる。

【実験のラウンドと環境の対応表】 練習パート 順序1 順序2 1 平常 平常 2 平常 平常 3 厳しい 厳しい 本番パート 順序1 順序2 1 平常 厳しい 2 厳しい 平常 3 平常 厳しい 4 厳しい 平常

実験は，上記の手順で進める。まず，実験参加の同意を得て，実験のタスクについて説明した後，目標の期中調整の告知ありの群には，目標の期中調整について説明する。目標の期中調整の告知なしの群には，期中調整の説明はしないが，厳しいラウンドがあることは説明する。 理解度チェックでは，参加者が実験のタスクや報酬についての問題すべてに正解するまで次の画面に進めないようにする。さらに，目標の期中調整の告知ありの群の参加者に対しては，期中調整の操作を理解しているかどうかを確認するための問題も含まれる。 理解度チェックの後，練習パートを行う。練習パートは，平常環境の2分間2回と厳しい環境のラウンド2分間1回を順番に行う。 その後，本番パートを実施する。本番パートの期首目標は，練習パートの2回目の平常ラウンドの正解数を2倍したものである（時間が2倍であるため）。これにより，参加者の能力に応じた目標設定ができる。なお，目標値が練習パートの実績に応じて決定されることは参加者には知らされない。目標の決定方法がわかっていれば，練習パートで努力を控える可能性があるためである。参加者は前半と後半1分間ずつの1回3分間のラウンドを8回行う。2回の平常環境のラウンド，2回の厳しい環境のラウンドで構成される。次のラウンドが平常環境であるか厳しい環境であるかは参加者に明示されない。また，厳しいピリオドと平常ピリオドの順序が参加者の行動に影響を与えるかどうかを評価するため，2パターンの順序を使用する。 前半と後半の間の中間フィードバックでは，前半の正解数とそのラウンドの目標値が表示される。そして，期中調整の実施ありの条件では，期中調整後の目標が表示される。調整後の目標は，本番ラウンドの時間が練習ラウンドの2倍であるため，練習パートの厳しいラウンドの正解数を2倍したものである。なお，目標の調整に関する参加者間の操作とラウンドの種類に関する参加者内の操作の効果を評価するため，各ラウンドの前半終了後と後半開始前に，参加者に割り当てられた目標の難易度を7段階で評価させる。 その後，参加者は，公正に関する認識，背景（年齢，性別，勤務年数）について質問に答える。これらの質問を終えると，参加者が獲得した金額を示すメッセージが表示される。参加者の報酬は，実験終了後にProlificを通じて各参加者に支払われる。

#### 報酬

練習パートでは1問正解するごとに£0.02の報酬が与えられる。本番パートの開始前に，参加者にそれぞれ目標値が提示される。目標値は練習パートにおける正解数に基づいて，参加者それぞれに目標値を設定する。参加者はラウンドごとに，目標の達成によってボーナスが£1.0与えられる。目標値を超える正解数には，1問あたり£0.1の割合で業績連動ボーナスが与えられる。ただし目標値を達成できなければそのラウンドの報酬は与えられない。例えば，目標が20問で実績が25問だった場合，目標達成ボーナスが1.0 £，業績連動ボーナスが£0.1×5問＝£0.5で合計£1.5である。 この報酬契約の設計は，標準的なインセンティブ契約を反映している。標準的なインセンティブ契約では，業績が目標レベルに達すればボーナスが支給され，業績が目標を上回れば，ボーナスは通常増額され，時には上限が設定されることもある (Jensen 2003, Murphy 2001)。ただし，報酬に上限を設定すると，参加者の業績が上限値に達したり近づいたりした場合，それ以上業績を高める努力を控える可能性が高い。今回の研究では目標の期中調整の効果を検証することが目的であり，目標の上限値が与える効果が目標の期中調整の効果と交絡することを防ぐため，今回は上限値を設定しない。 なお，報酬の総額がProlificによって規定されている最低時給（1時間あたり6£）に満たない場合は自動的に実験参加時間に見合った最低額が支給される 。

練習パート：1問正解ごとに£0.02 本番パート：目標達成により£0.6，目標を超過した正解数に対し1問あたり£0.02の追加ボーナスを支払う。 全参加者の完了時間の中央値から，prolificにおける最低時給（£6.0/h）を下回る場合は、自動的に上方修正される。実験の想定所要時間は30分（うち実験タスクの時間は19分）である。

予算 全員が練習パートで計30点を獲得し，本番パートで全ラウンドで目標を5点超過した場合 200人×（£0.6＋£0.6＋(0.02×5)×8）＝ 200人×£6.2 ＝ £1,240 クラウドソーシングサービス利用料（総報酬額の25%） £1,240×25％ ＝ £310 計　£1,550（£1＝200 円の場合，315,000円) サーバー利用料 5,000円 合計費用 320,000円

## 変数

### 説明変数

この研究の説明変数は，目標の期中調整の告知と実施である。第1の説明変数は，目標期中調整の告知である。「告知あり」条件の参加者には，参加者に「期首に設定された目標にあなたの業績が到達しないことにより，あなたのボーナス獲得の機会に悪影響を及ぼすため，50％の確率で適切な水準まで目標が下方調整される」と説明される。50％という確率を明示したのは，参加者に必ず調整されたりまったく調整されなかったりするだろうという偏った予想を抱かせないためである。ただし，(1)どのような条件で目標を調整するか（平常ラウンドか厳しいラウンドか），(2)目標の調整の具体的な大きさを事前に約束することはなかった。標が下方修正されるかどうかという不確実性を作り出すためである。また，「告知なし」条件には，期中調整の説明はしないが，厳しいラウンドが存在することは説明する。 　第2の説明変数は，期中調整の実施の有無である。平常ラウンドの「実施あり」「実施なし」の両条件と厳しいラウンドの「実施なし」条件では，期中調整は行われず，中間フィードバック（前半の正解数と期首に割り当てられた目標値）が表示される。厳しいラウンドの「実施あり」条件では，中間フィードバックと期中調整後の目標が表示される。調整後の目標は，練習パートの厳しいラウンドの正解数を2倍したものである。

### 被説明変数

本論文の被説明変数は，実験タスクの正解数である。仮説1の検証は全部のラウンドの前半の正解数，仮説2の検証は厳しいラウンドの後半の正解数，仮説3の検証は全部のラウンドの正解数を用いる。

### 公正の認識

　実験後の質問において，参加者に公正に関する質問をする。公正の認識を捉えるために、先行研究（Leventhal 1980; Thibaut, and Walker 1975）で開発され、最近では Colquitt (2001) によって検証された手続き的公正と分配的公正の尺度の修正版を使用する。このリストはKelly et al. (2015)でも用いられている。各尺度に含まれる項目は以下のとおりである。

1.  Process used to determine incentive payouts applied consistently. （インセンティブの支払い額を決定するプロセスが一貫して適用されている。）
2.  Process used to determine incentive payout has been fair. （インセンティブの支払い額を決定するプロセスが公平である。）
3.  Process used to determine incentive payout has been bias free. （インセンティブの支払い額を決定するプロセスにバイアスがない。）
4.  Amount of incentive payout received reflects effort I put into the task. （受け取ったインセンティブの支払い額は，私がタスクに費やした努力を反映している。）
5.  Incentive payout is appropriate for effort I have put into the task. （インセンティブの支払い額は，私がタスクに費やした努力に見合っている。）
6.  The amount of incentive payout reflects my contribution to the task. （インセンティブの支払い額は，タスクへの私の貢献を反映している。）
7.  The amount of payout is justified given my performance at the task. （タスクにおける自分の業績を考えれば，支払い額は正当である。）

## 結果

### 記述統計量

### マニピュレーション-チェック

-   平常ラウンドと厳しいラウンドで正解数が異なるか
-   期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度は，平常ラウンドよりも厳しいラウンドのほうが高いか
-   期中調整の告知ありの条件の参加者が認識する調整前の目標の難易度は，期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度よりも低いか
-   厳しいラウンドにおいて，期中調整の実施ありの条件で，参加者の認識する目標の難易度は，調整前よりも調整後のほうが低いか
-   厳しいラウンドにおいて，期中調整の実施ありの条件の参加者が認識する調整後の目標の難易度は，期中調整の実施なしの条件の参加者が認識する調整後の目標の難易度よりも低いか

### 仮説検定

-   仮説1a：平常環境の期待あり条件の前半業績の平均値vs. 平常環境の期待なし条件の前半業績の平均値のt検定
-   仮説1b：厳しい環境の期待あり条件の前半業績の平均値vs. 厳しい環境の期待なし条件の前半業績の平均値のt検定
-   仮説2： 1回目の厳しい環境の実施あり条件の後半業績vs. 1回目の厳しい環境の実施なし条件の後半業績のt検定 （厳しい環境の実施あり条件の後半業績の平均値vs. 厳しい環境の実施なし条件の後半業績の平均値のt検定）期待効果の交絡あり
-   仮説3a：期待あり-実施あり条件の手続き的公正の回答vs. 期待なし-実施あり条件の手続き的公正の回答のt検定
-   仮説3b：期待なし-実施あり条件の手続き的公正の回答vs. 期待なし-実施なし条件の手続き的公正の回答のt検定
-   仮説3c：期待あり-実施なし条件の手続き的公正の回答vs. 期待なし-実施なし条件の手続き的公正の回答のt検定
-   仮説4：手続き的公正の回答と全体業績の平均値の相関分析

#### 補足分析

被説明変数である業績と期待効果，実施効果，公正の認識，背景の説明変数のOLS

### パイロットテストの確認事項

-   目標難易度練習ラウンドに基づいた練習のスコア✕100％の目標が適切か -目標難易度の平均値-分散が偏っていないか -正解数の平均値-分散が偏っていないか

-   平常ラウンドのほうが厳しいラウンドよりも正解数が有意に多いか→◯

-   

-   期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度は，平常ラウンドよりも厳しいラウンドのほうが正解数が有意に高いか

-   期中調整の告知ありの条件の参加者が認識する調整前の目標の難易度は，期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度よりも有意に低いか

-   厳しいラウンドにおいて， -期中調整の実施ありの条件で，参加者の認識する目標の難易度は，調整前よりも調整後のほうが有意に低いか -期中調整の実施ありの条件で，参加者が認識する調整後の目標の難易度は，期中調整の実施なしの条件の参加者が認識する調整後の目標の難易度よりも有意に低いか

  ＜パイロットテスト計画＞ Yahoo! クラウドソーシングを利用

参加者100人程度 予算 基本料：1タスク10円（） 謝礼ポイント追加オプション：1.5円／1ポイント 1人　10円＋20ポイント✕1.5円＝40円 100人　40円✕100　＝　4,000円

仮想サーバー上の外部サイトに誘導→実験終了後に完了コードを入力してもらう

報酬は固定にするか

変動報酬は仕様上できない。 ただし報酬額ごとに追加タスクを設定する方法で変動報酬のようにすることは可能。

-   目標難易度練習ラウンドに基づいた練習のスコア✕100％の目標が適切か -目標難易度の平均値-分散が偏っていないか -正解数の平均値-分散が偏っていないか

### マニピュレーション-チェック

-   平常ラウンドのほうが厳しいラウンドよりも正解数が有意に多いか 仮説検証
-   期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度は，平常ラウンドよりも厳しいラウンドのほうが正解数が有意に高いか
-   期中調整の告知ありの条件の参加者が認識する調整前の目標の難易度は，期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度よりも有意に低いか
-   厳しいラウンドにおいて， -期中調整の実施ありの条件で，参加者の認識する目標の難易度は，調整前よりも調整後のほうが有意に低いか -期中調整の実施ありの条件で，参加者が認識する調整後の目標の難易度は，期中調整の実施なしの条件の参加者が認識する調整後の目標の難易度よりも有意に低いか

自己決定目標による実験に変更する 目標設定ボーナス 目標達成ボーナス 最終目標達成ボーナス
