---
title: "パイロットテスト結果"
author: "片岡　亮太"
format: html
editor: visual
date: now
date-format: YYYY/MM/DD, HH:mm
toc: true
toc-depth: 5
toc-location: left
toc-title: Contents
number-sections: true
number-depth: 5
code-fold: true
link-citations: true
---

## 実験計画の概要

### パイロットテストの確認事項

-   目標難易度練習ラウンドに基づいた練習のスコア✕100％の目標が適切か\

-   目標難易度の平均値-分散が偏っていないか

-   正解数の平均値-分散が偏っていないか

-   平常ラウンドのほうが厳しいラウンドよりも正解数が有意に多いか→◯

-   期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度は，平常ラウンドよりも厳しいラウンドのほうが正解数が有意に高いか

-   期中調整の告知ありの条件の参加者が認識する調整前の目標の難易度は，期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度よりも有意に低いか

-   厳しいラウンドにおいて， -期中調整の実施ありの条件で，参加者の認識する目標の難易度は，調整前よりも調整後のほうが有意に低いか -期中調整の実施ありの条件で，参加者が認識する調整後の目標の難易度は，期中調整の実施なしの条件の参加者が認識する調整後の目標の難易度よりも有意に低いか

  ＜パイロットテスト計画＞ Yahoo! クラウドソーシングを利用

参加者100人程度 予算 基本料：1タスク10円（） 謝礼ポイント追加オプション：1.5円／1ポイント 1人　10円＋20ポイント✕1.5円＝40円 100人　40円✕100　＝　4,000円

仮想サーバー上の外部サイトに誘導→実験終了後に完了コードを入力してもらう

報酬は固定にするか

変動報酬は仕様上できない。 ただし報酬額ごとに追加タスクを設定する方法で変動報酬のようにすることは可能。

-   目標難易度練習ラウンドに基づいた練習のスコア✕100％の目標が適切か\
-   目標難易度の平均値-分散が偏っていないか -正解数の平均値-分散が偏っていないか

### マニピュレーション・チェック

-   平常ラウンドのほうが厳しいラウンドよりも正解数が有意に多いか 仮説検証
-   期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度は，平常ラウンドよりも厳しいラウンドのほうが正解数が有意に高いか
-   期中調整の告知ありの条件の参加者が認識する調整前の目標の難易度は，期中調整の告知なしの条件の参加者が認識する調整前の目標の難易度よりも有意に低いか
-   厳しいラウンドにおいて，
    -   期中調整の実施ありの条件で，参加者の認識する目標の難易度は，調整前よりも調整後のほうが有意に低いか -期中調整の実施ありの条件で，参加者が認識する調整後の目標の難易度は，期中調整の実施なしの条件の参加者が認識する調整後の目標の難易度よりも有意に低いか

自己決定目標による実験に変更する 目標設定ボーナス 目標達成ボーナス 最終目標達成ボーナス
